apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-apps

resources:
  - ../../base

images:
  - name: ghcr.io/${{ values.repoUrl.owner }}/${{ values.name }}
    newTag: latest
